[book]
title = "Dasel Documentation"
authors = ["Tom Wright"]
language = "en"
src = "src"

[build]
build-dir = "book/v2"

[output.html]
git-repository-url = "https://github.com/TomWright/dasel-docs"
edit-url-template = "https://github.com/TomWright/dasel-docs/edit/v2/{path}"
additional-css = [
  "theme/version-switcher.css"
]
additional-js = [
  "theme/version-switcher.js"
]
